// <auto-generated />
using AspNet_Task.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNet_Task.Web.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AspNet_Task.Web.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Popular"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Featured"
                        });
                });

            modelBuilder.Entity("AspNet_Task.Web.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Color = "Yellow",
                            Description = "The phone that tells you jokes",
                            ImageUrl = "https://example.com/sillyphone.jpg",
                            Name = "Silly Smartphone",
                            Price = 99.99m,
                            SKU = "SKUSM001"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Color = "Purple",
                            Description = "A stylish hat for the trendsetters",
                            ImageUrl = "https://example.com/funkyfedora.jpg",
                            Name = "Funky Fedora",
                            Price = 49.99m,
                            SKU = "SKUFF001"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Color = "Green",
                            Description = "A clock that dances on your wall",
                            ImageUrl = "https://example.com/whimsicalclock.jpg",
                            Name = "Whimsical Wall Clock",
                            Price = 29.99m,
                            SKU = "SKUWC001"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Color = "Multi-color",
                            Description = "Stretch it, squish it, have endless fun",
                            ImageUrl = "https://example.com/goofygoo.jpg",
                            Name = "Goofy Goo",
                            Price = 9.99m,
                            SKU = "SKUGG001"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Color = "Black/White",
                            Description = "Skate in style with zebra stripes",
                            ImageUrl = "https://example.com/zebraskates.jpg",
                            Name = "Zany Zebra Roller Skates",
                            Price = 79.99m,
                            SKU = "SKUZS001"
                        });
                });

            modelBuilder.Entity("AspNet_Task.Web.Data.Models.Product", b =>
                {
                    b.HasOne("AspNet_Task.Web.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AspNet_Task.Web.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
